/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSupportoRouteImport } from './routes/_authenticated/supporto'
import { Route as AuthenticatedFatturazioneRouteImport } from './routes/_authenticated/fatturazione'
import { Route as AuthenticatedCostoTrasportoRouteImport } from './routes/_authenticated/costo-trasporto'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminUtentiRouteImport } from './routes/_authenticated/admin/utenti'
import { Route as AuthenticatedAdminSupportoRouteImport } from './routes/_authenticated/admin/supporto'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportoRoute = AuthenticatedSupportoRouteImport.update({
  id: '/supporto',
  path: '/supporto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFatturazioneRoute =
  AuthenticatedFatturazioneRouteImport.update({
    id: '/fatturazione',
    path: '/fatturazione',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCostoTrasportoRoute =
  AuthenticatedCostoTrasportoRouteImport.update({
    id: '/costo-trasporto',
    path: '/costo-trasporto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUtentiRoute =
  AuthenticatedAdminUtentiRouteImport.update({
    id: '/utenti',
    path: '/utenti',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupportoRoute =
  AuthenticatedAdminSupportoRouteImport.update({
    id: '/supporto',
    path: '/supporto',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/costo-trasporto': typeof AuthenticatedCostoTrasportoRoute
  '/fatturazione': typeof AuthenticatedFatturazioneRoute
  '/supporto': typeof AuthenticatedSupportoRoute
  '/admin/supporto': typeof AuthenticatedAdminSupportoRoute
  '/admin/utenti': typeof AuthenticatedAdminUtentiRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/costo-trasporto': typeof AuthenticatedCostoTrasportoRoute
  '/fatturazione': typeof AuthenticatedFatturazioneRoute
  '/supporto': typeof AuthenticatedSupportoRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/supporto': typeof AuthenticatedAdminSupportoRoute
  '/admin/utenti': typeof AuthenticatedAdminUtentiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/costo-trasporto': typeof AuthenticatedCostoTrasportoRoute
  '/_authenticated/fatturazione': typeof AuthenticatedFatturazioneRoute
  '/_authenticated/supporto': typeof AuthenticatedSupportoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/supporto': typeof AuthenticatedAdminSupportoRoute
  '/_authenticated/admin/utenti': typeof AuthenticatedAdminUtentiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/costo-trasporto'
    | '/fatturazione'
    | '/supporto'
    | '/admin/supporto'
    | '/admin/utenti'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/costo-trasporto'
    | '/fatturazione'
    | '/supporto'
    | '/'
    | '/admin/supporto'
    | '/admin/utenti'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/costo-trasporto'
    | '/_authenticated/fatturazione'
    | '/_authenticated/supporto'
    | '/_authenticated/'
    | '/_authenticated/admin/supporto'
    | '/_authenticated/admin/utenti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supporto': {
      id: '/_authenticated/supporto'
      path: '/supporto'
      fullPath: '/supporto'
      preLoaderRoute: typeof AuthenticatedSupportoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fatturazione': {
      id: '/_authenticated/fatturazione'
      path: '/fatturazione'
      fullPath: '/fatturazione'
      preLoaderRoute: typeof AuthenticatedFatturazioneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costo-trasporto': {
      id: '/_authenticated/costo-trasporto'
      path: '/costo-trasporto'
      fullPath: '/costo-trasporto'
      preLoaderRoute: typeof AuthenticatedCostoTrasportoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/utenti': {
      id: '/_authenticated/admin/utenti'
      path: '/utenti'
      fullPath: '/admin/utenti'
      preLoaderRoute: typeof AuthenticatedAdminUtentiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/supporto': {
      id: '/_authenticated/admin/supporto'
      path: '/supporto'
      fullPath: '/admin/supporto'
      preLoaderRoute: typeof AuthenticatedAdminSupportoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSupportoRoute: typeof AuthenticatedAdminSupportoRoute
  AuthenticatedAdminUtentiRoute: typeof AuthenticatedAdminUtentiRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSupportoRoute: AuthenticatedAdminSupportoRoute,
    AuthenticatedAdminUtentiRoute: AuthenticatedAdminUtentiRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCostoTrasportoRoute: typeof AuthenticatedCostoTrasportoRoute
  AuthenticatedFatturazioneRoute: typeof AuthenticatedFatturazioneRoute
  AuthenticatedSupportoRoute: typeof AuthenticatedSupportoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCostoTrasportoRoute: AuthenticatedCostoTrasportoRoute,
  AuthenticatedFatturazioneRoute: AuthenticatedFatturazioneRoute,
  AuthenticatedSupportoRoute: AuthenticatedSupportoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
